<?php namespace Keios\ProUser\Updates;

use October\Rain\Database\Updates\Seeder;
use Keios\ProUser\Models\Country;

/**
 * Class SeedAllTables
 * @package Keios\ProUser\Updates
 */
class SeedAllTables extends Seeder
{

    public function run()
    {
        Country::insert(
            [
                ['is_enabled' => true, 'code' => 'AF', 'name' => 'Afghanistan'],
                ['is_enabled' => true, 'code' => 'AX', 'name' => 'Aland Islands '],
                ['is_enabled' => true, 'code' => 'AL', 'name' => 'Albania'],
                ['is_enabled' => true, 'code' => 'DZ', 'name' => 'Algeria'],
                ['is_enabled' => true, 'code' => 'AS', 'name' => 'American Samoa'],
                ['is_enabled' => true, 'code' => 'AD', 'name' => 'Andorra'],
                ['is_enabled' => true, 'code' => 'AO', 'name' => 'Angola'],
                ['is_enabled' => true, 'code' => 'AI', 'name' => 'Anguilla'],
                ['is_enabled' => true, 'code' => 'AQ', 'name' => 'Antarctica'],
                ['is_enabled' => true, 'code' => 'AG', 'name' => 'Antigua and Barbuda'],
                ['is_enabled' => true, 'code' => 'AR', 'name' => 'Argentina'],
                ['is_enabled' => true, 'code' => 'AM', 'name' => 'Armenia'],
                ['is_enabled' => true, 'code' => 'AW', 'name' => 'Aruba'],
                ['is_enabled' => true, 'code' => 'AU', 'name' => 'Australia'],
                ['is_enabled' => true, 'code' => 'AT', 'name' => 'Austria'],
                ['is_enabled' => true, 'code' => 'AZ', 'name' => 'Azerbaijan'],
                ['is_enabled' => true, 'code' => 'BS', 'name' => 'Bahamas'],
                ['is_enabled' => true, 'code' => 'BH', 'name' => 'Bahrain'],
                ['is_enabled' => true, 'code' => 'BD', 'name' => 'Bangladesh'],
                ['is_enabled' => true, 'code' => 'BB', 'name' => 'Barbados'],
                ['is_enabled' => true, 'code' => 'BY', 'name' => 'Belarus'],
                ['is_enabled' => true, 'code' => 'BZ', 'name' => 'Belize'],
                ['is_enabled' => true, 'code' => 'BE', 'name' => 'Belgium'],
                ['is_enabled' => true, 'code' => 'BJ', 'name' => 'Benin'],
                ['is_enabled' => true, 'code' => 'BM', 'name' => 'Bermuda'],
                ['is_enabled' => true, 'code' => 'BT', 'name' => 'Bhutan'],
                ['is_enabled' => true, 'code' => 'BO', 'name' => 'Bolivia, Plurinational State of'],
                ['is_enabled' => true, 'code' => 'BQ', 'name' => 'Bonaire, Sint Eustatius and Saba'],
                ['is_enabled' => true, 'code' => 'BA', 'name' => 'Bosnia and Herzegovina'],
                ['is_enabled' => true, 'code' => 'BW', 'name' => 'Botswana'],
                ['is_enabled' => true, 'code' => 'BV', 'name' => 'Bouvet Island'],
                ['is_enabled' => true, 'code' => 'BR', 'name' => 'Brazil'],
                ['is_enabled' => true, 'code' => 'IO', 'name' => 'British Indian Ocean Territory'],
                ['is_enabled' => true, 'code' => 'BN', 'name' => 'Brunei Darussalam'],
                ['is_enabled' => true, 'code' => 'BG', 'name' => 'Bulgaria'],
                ['is_enabled' => true, 'code' => 'BF', 'name' => 'Burkina Faso'],
                ['is_enabled' => true, 'code' => 'BI', 'name' => 'Burundi'],
                ['is_enabled' => true, 'code' => 'KH', 'name' => 'Cambodia'],
                ['is_enabled' => true, 'code' => 'CM', 'name' => 'Cameroon'],
                ['is_enabled' => true, 'code' => 'CA', 'name' => 'Canada'],
                ['is_enabled' => true, 'code' => 'CV', 'name' => 'Cape Verde'],
                ['is_enabled' => true, 'code' => 'KY', 'name' => 'Cayman Islands'],
                ['is_enabled' => true, 'code' => 'CF', 'name' => 'Central African Republic'],
                ['is_enabled' => true, 'code' => 'TD', 'name' => 'Chad'],
                ['is_enabled' => true, 'code' => 'CL', 'name' => 'Chile'],
                ['is_enabled' => true, 'code' => 'CN', 'name' => 'China'],
                ['is_enabled' => true, 'code' => 'CX', 'name' => 'Christmas Island'],
                ['is_enabled' => true, 'code' => 'CC', 'name' => 'Cocos (Keeling) Islands'],
                ['is_enabled' => true, 'code' => 'CO', 'name' => 'Colombia'],
                ['is_enabled' => true, 'code' => 'KM', 'name' => 'Comoros'],
                ['is_enabled' => true, 'code' => 'CG', 'name' => 'Congo'],
                ['is_enabled' => true, 'code' => 'CD', 'name' => 'Congo, the Democratic Republic of the'],
                ['is_enabled' => true, 'code' => 'CK', 'name' => 'Cook Islands'],
                ['is_enabled' => true, 'code' => 'CR', 'name' => 'Costa Rica'],
                ['is_enabled' => true, 'code' => 'CI', 'name' => 'Cote d\'Ivoire'],
                ['is_enabled' => true, 'code' => 'HR', 'name' => 'Croatia'],
                ['is_enabled' => true, 'code' => 'CU', 'name' => 'Cuba'],
                ['is_enabled' => true, 'code' => 'CW', 'name' => 'Curaçao'],
                ['is_enabled' => true, 'code' => 'CY', 'name' => 'Cyprus'],
                ['is_enabled' => true, 'code' => 'CZ', 'name' => 'Czech Republic'],
                ['is_enabled' => true, 'code' => 'DK', 'name' => 'Denmark'],
                ['is_enabled' => true, 'code' => 'DJ', 'name' => 'Djibouti'],
                ['is_enabled' => true, 'code' => 'DM', 'name' => 'Dominica'],
                ['is_enabled' => true, 'code' => 'DO', 'name' => 'Dominican Republic'],
                ['is_enabled' => true, 'code' => 'EC', 'name' => 'Ecuador'],
                ['is_enabled' => true, 'code' => 'EG', 'name' => 'Egypt'],
                ['is_enabled' => true, 'code' => 'SV', 'name' => 'El Salvador'],
                ['is_enabled' => true, 'code' => 'GQ', 'name' => 'Equatorial Guinea'],
                ['is_enabled' => true, 'code' => 'ER', 'name' => 'Eritrea'],
                ['is_enabled' => true, 'code' => 'EE', 'name' => 'Estonia'],
                ['is_enabled' => true, 'code' => 'ET', 'name' => 'Ethiopia'],
                ['is_enabled' => true, 'code' => 'FK', 'name' => 'Falkland Islands (Malvinas)'],
                ['is_enabled' => true, 'code' => 'FO', 'name' => 'Faroe Islands'],
                ['is_enabled' => true, 'code' => 'FJ', 'name' => 'Fiji'],
                ['is_enabled' => true, 'code' => 'FI', 'name' => 'Finland'],
                ['is_enabled' => true, 'code' => 'GF', 'name' => 'French Guiana'],
                ['is_enabled' => true, 'code' => 'PF', 'name' => 'French Polynesia'],
                ['is_enabled' => true, 'code' => 'TF', 'name' => 'French Southern Territories'],
                ['is_enabled' => true, 'code' => 'GA', 'name' => 'Gabon'],
                ['is_enabled' => true, 'code' => 'GM', 'name' => 'Gambia'],
                ['is_enabled' => true, 'code' => 'GE', 'name' => 'Georgia'],
                ['is_enabled' => true, 'code' => 'DE', 'name' => 'Germany'],
                ['is_enabled' => true, 'code' => 'GH', 'name' => 'Ghana'],
                ['is_enabled' => true, 'code' => 'GI', 'name' => 'Gibraltar'],
                ['is_enabled' => true, 'code' => 'GR', 'name' => 'Greece'],
                ['is_enabled' => true, 'code' => 'GL', 'name' => 'Greenland'],
                ['is_enabled' => true, 'code' => 'GD', 'name' => 'Grenada'],
                ['is_enabled' => true, 'code' => 'GP', 'name' => 'Guadeloupe'],
                ['is_enabled' => true, 'code' => 'GU', 'name' => 'Guam'],
                ['is_enabled' => true, 'code' => 'GT', 'name' => 'Guatemala'],
                ['is_enabled' => true, 'code' => 'GG', 'name' => 'Guernsey'],
                ['is_enabled' => true, 'code' => 'GN', 'name' => 'Guinea'],
                ['is_enabled' => true, 'code' => 'GW', 'name' => 'Guinea-Bissau'],
                ['is_enabled' => true, 'code' => 'GY', 'name' => 'Guyana'],
                ['is_enabled' => true, 'code' => 'HT', 'name' => 'Haiti'],
                ['is_enabled' => true, 'code' => 'HM', 'name' => 'Heard Island and McDonald Islands'],
                ['is_enabled' => true, 'code' => 'VA', 'name' => 'Holy See (Vatican City State)'],
                ['is_enabled' => true, 'code' => 'HN', 'name' => 'Honduras'],
                ['is_enabled' => true, 'code' => 'HK', 'name' => 'Hong Kong'],
                ['is_enabled' => true, 'code' => 'HU', 'name' => 'Hungary'],
                ['is_enabled' => true, 'code' => 'IS', 'name' => 'Iceland'],
                ['is_enabled' => true, 'code' => 'IN', 'name' => 'India'],
                ['is_enabled' => true, 'code' => 'ID', 'name' => 'Indonesia'],
                ['is_enabled' => true, 'code' => 'IR', 'name' => 'Iran, Islamic Republic of'],
                ['is_enabled' => true, 'code' => 'IQ', 'name' => 'Iraq'],
                ['is_enabled' => true, 'code' => 'IE', 'name' => 'Ireland'],
                ['is_enabled' => true, 'code' => 'IM', 'name' => 'Isle of Man'],
                ['is_enabled' => true, 'code' => 'IL', 'name' => 'Israel'],
                ['is_enabled' => true, 'code' => 'IT', 'name' => 'Italy'],
                ['is_enabled' => true, 'code' => 'JM', 'name' => 'Jamaica'],
                ['is_enabled' => true, 'code' => 'JP', 'name' => 'Japan'],
                ['is_enabled' => true, 'code' => 'JE', 'name' => 'Jersey'],
                ['is_enabled' => true, 'code' => 'JO', 'name' => 'Jordan'],
                ['is_enabled' => true, 'code' => 'KZ', 'name' => 'Kazakhstan'],
                ['is_enabled' => true, 'code' => 'KE', 'name' => 'Kenya'],
                ['is_enabled' => true, 'code' => 'KI', 'name' => 'Kiribati'],
                ['is_enabled' => true, 'code' => 'KP', 'name' => 'Korea, Democratic People\'s Republic of'],
                ['is_enabled' => true, 'code' => 'KR', 'name' => 'Korea, Republic of'],
                ['is_enabled' => true, 'code' => 'KW', 'name' => 'Kuwait'],
                ['is_enabled' => true, 'code' => 'KG', 'name' => 'Kyrgyzstan'],
                ['is_enabled' => true, 'code' => 'LA', 'name' => 'Lao People\'s Democratic Republic'],
                ['is_enabled' => true, 'code' => 'LV', 'name' => 'Latvia'],
                ['is_enabled' => true, 'code' => 'LB', 'name' => 'Lebanon'],
                ['is_enabled' => true, 'code' => 'LS', 'name' => 'Lesotho'],
                ['is_enabled' => true, 'code' => 'LR', 'name' => 'Liberia'],
                ['is_enabled' => true, 'code' => 'LY', 'name' => 'Libyan Arab Jamahiriya'],
                ['is_enabled' => true, 'code' => 'LI', 'name' => 'Liechtenstein'],
                ['is_enabled' => true, 'code' => 'LT', 'name' => 'Lithuania'],
                ['is_enabled' => true, 'code' => 'LU', 'name' => 'Luxembourg'],
                ['is_enabled' => true, 'code' => 'MO', 'name' => 'Macao'],
                ['is_enabled' => true, 'code' => 'MK', 'name' => 'Macedonia'],
                ['is_enabled' => true, 'code' => 'MG', 'name' => 'Madagascar'],
                ['is_enabled' => true, 'code' => 'MW', 'name' => 'Malawi'],
                ['is_enabled' => true, 'code' => 'MY', 'name' => 'Malaysia'],
                ['is_enabled' => true, 'code' => 'MV', 'name' => 'Maldives'],
                ['is_enabled' => true, 'code' => 'ML', 'name' => 'Mali'],
                ['is_enabled' => true, 'code' => 'MT', 'name' => 'Malta'],
                ['is_enabled' => true, 'code' => 'MH', 'name' => 'Marshall Islands'],
                ['is_enabled' => true, 'code' => 'MQ', 'name' => 'Martinique'],
                ['is_enabled' => true, 'code' => 'MR', 'name' => 'Mauritania'],
                ['is_enabled' => true, 'code' => 'MU', 'name' => 'Mauritius'],
                ['is_enabled' => true, 'code' => 'YT', 'name' => 'Mayotte'],
                ['is_enabled' => true, 'code' => 'MX', 'name' => 'Mexico'],
                ['is_enabled' => true, 'code' => 'FM', 'name' => 'Micronesia, Federated States of'],
                ['is_enabled' => true, 'code' => 'MD', 'name' => 'Moldova, Republic of'],
                ['is_enabled' => true, 'code' => 'MC', 'name' => 'Monaco'],
                ['is_enabled' => true, 'code' => 'MN', 'name' => 'Mongolia'],
                ['is_enabled' => true, 'code' => 'ME', 'name' => 'Montenegro'],
                ['is_enabled' => true, 'code' => 'MS', 'name' => 'Montserrat'],
                ['is_enabled' => true, 'code' => 'MA', 'name' => 'Morocco'],
                ['is_enabled' => true, 'code' => 'MZ', 'name' => 'Mozambique'],
                ['is_enabled' => true, 'code' => 'MM', 'name' => 'Myanmar'],
                ['is_enabled' => true, 'code' => 'NA', 'name' => 'Namibia'],
                ['is_enabled' => true, 'code' => 'NR', 'name' => 'Nauru'],
                ['is_enabled' => true, 'code' => 'NP', 'name' => 'Nepal'],
                ['is_enabled' => true, 'code' => 'NL', 'name' => 'Netherlands'],
                ['is_enabled' => true, 'code' => 'NC', 'name' => 'New Caledonia'],
                ['is_enabled' => true, 'code' => 'NZ', 'name' => 'New Zealand'],
                ['is_enabled' => true, 'code' => 'NI', 'name' => 'Nicaragua'],
                ['is_enabled' => true, 'code' => 'NE', 'name' => 'Niger'],
                ['is_enabled' => true, 'code' => 'NG', 'name' => 'Nigeria'],
                ['is_enabled' => true, 'code' => 'NU', 'name' => 'Niue'],
                ['is_enabled' => true, 'code' => 'NF', 'name' => 'Norfolk Island'],
                ['is_enabled' => true, 'code' => 'MP', 'name' => 'Northern Mariana Islands'],
                ['is_enabled' => true, 'code' => 'NO', 'name' => 'Norway'],
                ['is_enabled' => true, 'code' => 'OM', 'name' => 'Oman'],
                ['is_enabled' => true, 'code' => 'PK', 'name' => 'Pakistan'],
                ['is_enabled' => true, 'code' => 'PW', 'name' => 'Palau'],
                ['is_enabled' => true, 'code' => 'PS', 'name' => 'Palestinian Territory, Occupied'],
                ['is_enabled' => true, 'code' => 'PA', 'name' => 'Panama'],
                ['is_enabled' => true, 'code' => 'PG', 'name' => 'Papua New Guinea'],
                ['is_enabled' => true, 'code' => 'PY', 'name' => 'Paraguay'],
                ['is_enabled' => true, 'code' => 'PE', 'name' => 'Peru'],
                ['is_enabled' => true, 'code' => 'PH', 'name' => 'Philippines'],
                ['is_enabled' => true, 'code' => 'PN', 'name' => 'Pitcairn'],
                ['is_enabled' => true, 'code' => 'PL', 'name' => 'Poland'],
                ['is_enabled' => true, 'code' => 'PT', 'name' => 'Portugal'],
                ['is_enabled' => true, 'code' => 'PR', 'name' => 'Puerto Rico'],
                ['is_enabled' => true, 'code' => 'QA', 'name' => 'Qatar'],
                ['is_enabled' => true, 'code' => 'RE', 'name' => 'Reunion'],
                ['is_enabled' => true, 'code' => 'RO', 'name' => 'Romania'],
                ['is_enabled' => true, 'code' => 'RU', 'name' => 'Russian Federation'],
                ['is_enabled' => true, 'code' => 'RW', 'name' => 'Rwanda'],
                ['is_enabled' => true, 'code' => 'BL', 'name' => 'Saint Barthélemy'],
                ['is_enabled' => true, 'code' => 'SH', 'name' => 'Saint Helena'],
                ['is_enabled' => true, 'code' => 'KN', 'name' => 'Saint Kitts and Nevis'],
                ['is_enabled' => true, 'code' => 'LC', 'name' => 'Saint Lucia'],
                ['is_enabled' => true, 'code' => 'MF', 'name' => 'Saint Martin (French part)'],
                ['is_enabled' => true, 'code' => 'PM', 'name' => 'Saint Pierre and Miquelon'],
                ['is_enabled' => true, 'code' => 'VC', 'name' => 'Saint Vincent and the Grenadines'],
                ['is_enabled' => true, 'code' => 'WS', 'name' => 'Samoa'],
                ['is_enabled' => true, 'code' => 'SM', 'name' => 'San Marino'],
                ['is_enabled' => true, 'code' => 'ST', 'name' => 'Sao Tome and Principe'],
                ['is_enabled' => true, 'code' => 'SA', 'name' => 'Saudi Arabia'],
                ['is_enabled' => true, 'code' => 'SN', 'name' => 'Senegal'],
                ['is_enabled' => true, 'code' => 'RS', 'name' => 'Serbia'],
                ['is_enabled' => true, 'code' => 'SC', 'name' => 'Seychelles'],
                ['is_enabled' => true, 'code' => 'SL', 'name' => 'Sierra Leone'],
                ['is_enabled' => true, 'code' => 'SG', 'name' => 'Singapore'],
                ['is_enabled' => true, 'code' => 'SX', 'name' => 'Sint Maarten (Dutch part)'],
                ['is_enabled' => true, 'code' => 'SK', 'name' => 'Slovakia'],
                ['is_enabled' => true, 'code' => 'SI', 'name' => 'Slovenia'],
                ['is_enabled' => true, 'code' => 'SB', 'name' => 'Solomon Islands'],
                ['is_enabled' => true, 'code' => 'SO', 'name' => 'Somalia'],
                ['is_enabled' => true, 'code' => 'ZA', 'name' => 'South Africa'],
                ['is_enabled' => true, 'code' => 'GS', 'name' => 'South Georgia and the South Sandwich Islands'],
                ['is_enabled' => true, 'code' => 'ES', 'name' => 'Spain'],
                ['is_enabled' => true, 'code' => 'LK', 'name' => 'Sri Lanka'],
                ['is_enabled' => true, 'code' => 'SD', 'name' => 'Sudan'],
                ['is_enabled' => true, 'code' => 'SR', 'name' => 'Suriname'],
                ['is_enabled' => true, 'code' => 'SJ', 'name' => 'Svalbard and Jan Mayen'],
                ['is_enabled' => true, 'code' => 'SZ', 'name' => 'Swaziland'],
                ['is_enabled' => true, 'code' => 'SE', 'name' => 'Sweden'],
                ['is_enabled' => true, 'code' => 'CH', 'name' => 'Switzerland'],
                ['is_enabled' => true, 'code' => 'SY', 'name' => 'Syrian Arab Republic'],
                ['is_enabled' => true, 'code' => 'TW', 'name' => 'Taiwan, Province of China'],
                ['is_enabled' => true, 'code' => 'TJ', 'name' => 'Tajikistan'],
                ['is_enabled' => true, 'code' => 'TZ', 'name' => 'Tanzania, United Republic of'],
                ['is_enabled' => true, 'code' => 'TH', 'name' => 'Thailand'],
                ['is_enabled' => true, 'code' => 'TL', 'name' => 'Timor-Leste'],
                ['is_enabled' => true, 'code' => 'TG', 'name' => 'Togo'],
                ['is_enabled' => true, 'code' => 'TK', 'name' => 'Tokelau'],
                ['is_enabled' => true, 'code' => 'TO', 'name' => 'Tonga'],
                ['is_enabled' => true, 'code' => 'TT', 'name' => 'Trinidad and Tobago'],
                ['is_enabled' => true, 'code' => 'TN', 'name' => 'Tunisia'],
                ['is_enabled' => true, 'code' => 'TR', 'name' => 'Turkey'],
                ['is_enabled' => true, 'code' => 'TM', 'name' => 'Turkmenistan'],
                ['is_enabled' => true, 'code' => 'TC', 'name' => 'Turks and Caicos Islands'],
                ['is_enabled' => true, 'code' => 'TV', 'name' => 'Tuvalu'],
                ['is_enabled' => true, 'code' => 'UG', 'name' => 'Uganda'],
                ['is_enabled' => true, 'code' => 'UA', 'name' => 'Ukraine'],
                ['is_enabled' => true, 'code' => 'AE', 'name' => 'United Arab Emirates'],
                ['is_enabled' => true, 'code' => 'GB', 'name' => 'United Kingdom'],
                ['is_enabled' => true, 'code' => 'US', 'name' => 'United States'],
                ['is_enabled' => true, 'code' => 'UM', 'name' => 'United States Minor Outlying Islands'],
                ['is_enabled' => true, 'code' => 'UY', 'name' => 'Uruguay'],
                ['is_enabled' => true, 'code' => 'UZ', 'name' => 'Uzbekistan'],
                ['is_enabled' => true, 'code' => 'VU', 'name' => 'Vanuatu'],
                ['is_enabled' => true, 'code' => 'VE', 'name' => 'Venezuela, Bolivarian Republic of'],
                ['is_enabled' => true, 'code' => 'VN', 'name' => 'Viet Nam'],
                ['is_enabled' => true, 'code' => 'VG', 'name' => 'Virgin Islands, British'],
                ['is_enabled' => true, 'code' => 'VI', 'name' => 'Virgin Islands, U.S.'],
                ['is_enabled' => true, 'code' => 'WF', 'name' => 'Wallis and Futuna'],
                ['is_enabled' => true, 'code' => 'EH', 'name' => 'Western Sahara'],
                ['is_enabled' => true, 'code' => 'YE', 'name' => 'Yemen'],
                ['is_enabled' => true, 'code' => 'ZM', 'name' => 'Zambia'],
                ['is_enabled' => true, 'code' => 'ZW', 'name' => 'Zimbabwe'],
            ]
        );

        $us = Country::whereCode('US')->first();
        $us->states()->createMany(
            [
                ['code' => 'AL', 'name' => 'Alabama'],
                ['code' => 'AK', 'name' => 'Alaska'],
                ['code' => 'AS', 'name' => 'American Samoa'],
                ['code' => 'AZ', 'name' => 'Arizona'],
                ['code' => 'AR', 'name' => 'Arkansas'],
                ['code' => 'CA', 'name' => 'California'],
                ['code' => 'CO', 'name' => 'Colorado'],
                ['code' => 'CT', 'name' => 'Connecticut'],
                ['code' => 'DE', 'name' => 'Delaware'],
                ['code' => 'DC', 'name' => 'Dist. of Columbia'],
                ['code' => 'FL', 'name' => 'Florida'],
                ['code' => 'GA', 'name' => 'Georgia'],
                ['code' => 'GU', 'name' => 'Guam'],
                ['code' => 'HI', 'name' => 'Hawaii'],
                ['code' => 'ID', 'name' => 'Idaho'],
                ['code' => 'IL', 'name' => 'Illinois'],
                ['code' => 'IN', 'name' => 'Indiana'],
                ['code' => 'IA', 'name' => 'Iowa'],
                ['code' => 'KS', 'name' => 'Kansas'],
                ['code' => 'KY', 'name' => 'Kentucky'],
                ['code' => 'LA', 'name' => 'Louisiana'],
                ['code' => 'ME', 'name' => 'Maine'],
                ['code' => 'MD', 'name' => 'Maryland'],
                ['code' => 'MH', 'name' => 'Marshall Islands'],
                ['code' => 'MA', 'name' => 'Massachusetts'],
                ['code' => 'MI', 'name' => 'Michigan'],
                ['code' => 'FM', 'name' => 'Micronesia'],
                ['code' => 'MN', 'name' => 'Minnesota'],
                ['code' => 'MS', 'name' => 'Mississippi'],
                ['code' => 'MO', 'name' => 'Missouri'],
                ['code' => 'MT', 'name' => 'Montana'],
                ['code' => 'NE', 'name' => 'Nebraska'],
                ['code' => 'NV', 'name' => 'Nevada'],
                ['code' => 'NH', 'name' => 'New Hampshire'],
                ['code' => 'NJ', 'name' => 'New Jersey'],
                ['code' => 'NM', 'name' => 'New Mexico'],
                ['code' => 'NY', 'name' => 'New York'],
                ['code' => 'NC', 'name' => 'North Carolina'],
                ['code' => 'ND', 'name' => 'North Dakota'],
                ['code' => 'MP', 'name' => 'Northern Marianas'],
                ['code' => 'OH', 'name' => 'Ohio'],
                ['code' => 'OK', 'name' => 'Oklahoma'],
                ['code' => 'OR', 'name' => 'Oregon'],
                ['code' => 'PW', 'name' => 'Palau'],
                ['code' => 'PA', 'name' => 'Pennsylvania'],
                ['code' => 'PR', 'name' => 'Puerto Rico'],
                ['code' => 'RI', 'name' => 'Rhode Island'],
                ['code' => 'SC', 'name' => 'South Carolina'],
                ['code' => 'SD', 'name' => 'South Dakota'],
                ['code' => 'TN', 'name' => 'Tennessee'],
                ['code' => 'TX', 'name' => 'Texas'],
                ['code' => 'UT', 'name' => 'Utah'],
                ['code' => 'VT', 'name' => 'Vermont'],
                ['code' => 'VA', 'name' => 'Virginia'],
                ['code' => 'VI', 'name' => 'Virgin Islands'],
                ['code' => 'WA', 'name' => 'Washington'],
                ['code' => 'WV', 'name' => 'West Virginia'],
                ['code' => 'WI', 'name' => 'Wisconsin'],
                ['code' => 'WY', 'name' => 'Wyoming'],
            ]
        );

        $ca = Country::whereCode('CA')->first();
        $ca->states()->createMany(
            [
                ['code' => 'AB', 'name' => 'Alberta'],
                ['code' => 'BC', 'name' => 'British Columbia'],
                ['code' => 'MB', 'name' => 'Manitoba'],
                ['code' => 'NB', 'name' => 'New Brunswick'],
                ['code' => 'NL', 'name' => 'Newfoundland and Labrador'],
                ['code' => 'NT', 'name' => 'Northwest Territories'],
                ['code' => 'NS', 'name' => 'Nova Scotia'],
                ['code' => 'NU', 'name' => 'Nunavut'],
                ['code' => 'ON', 'name' => 'Ontario'],
                ['code' => 'PE', 'name' => 'Prince Edward Island'],
                ['code' => 'QC', 'name' => 'Quebec'],
                ['code' => 'SK', 'name' => 'Saskatchewan'],
                ['code' => 'YT', 'name' => 'Yukon'],
            ]
        );

        $au = Country::whereCode('AU')->first();
        $au->states()->createMany(
            [
                ['code' => 'NSW', 'name' => 'New South Wales'],
                ['code' => 'QLD', 'name' => 'Queensland'],
                ['code' => 'SA', 'name' => 'South Australia'],
                ['code' => 'TAS', 'name' => 'Tasmania'],
                ['code' => 'VIC', 'name' => 'Victoria'],
                ['code' => 'WA', 'name' => 'Western Australia'],
                ['code' => 'NT', 'name' => 'Northern Territory'],
                ['code' => 'ACT', 'name' => 'Australian Capital Territory'],
            ]
        );

        $de = Country::whereCode('DE')->first();
        $de->states()->createMany(
            [
                ['code' => 'BW', 'name' => 'Baden-Württemberg'],
                ['code' => 'BY', 'name' => 'Bavaria'],
                ['code' => 'BE', 'name' => 'Berlin'],
                ['code' => 'BB', 'name' => 'Brandenburg'],
                ['code' => 'HB', 'name' => 'Bremen'],
                ['code' => 'HH', 'name' => 'Hamburg'],
                ['code' => 'HE', 'name' => 'Hesse'],
                ['code' => 'MV', 'name' => 'Mecklenburg-Vorpommern'],
                ['code' => 'NI', 'name' => 'Lower Saxony'],
                ['code' => 'NW', 'name' => 'North Rhine-Westphalia'],
                ['code' => 'RP', 'name' => 'Rhineland-Palatinate'],
                ['code' => 'SL', 'name' => 'Saarland'],
                ['code' => 'SN', 'name' => 'Saxony'],
                ['code' => 'ST', 'name' => 'Saxony-Anhalt'],
                ['code' => 'SH', 'name' => 'Schleswig-Holstein'],
                ['code' => 'TH', 'name' => 'Thuringia'],
            ]
        );

        $ie = Country::whereCode('IE')->first();
        $ie->states()->createMany(
            [
                ['code' => 'D', 'name' => 'Dublin'],
                ['code' => 'WW', 'name' => 'Wicklow'],
                ['code' => 'WX', 'name' => 'Wexford'],
                ['code' => 'CW', 'name' => 'Carlow'],
                ['code' => 'KE', 'name' => 'Kildare'],
                ['code' => 'MH', 'name' => 'Meath'],
                ['code' => 'LH', 'name' => 'Louth'],
                ['code' => 'MN', 'name' => 'Monaghan'],
                ['code' => 'CN', 'name' => 'Cavan'],
                ['code' => 'LD', 'name' => 'Longford'],
                ['code' => 'WH', 'name' => 'Westmeath'],
                ['code' => 'OY', 'name' => 'Offaly'],
                ['code' => 'LS', 'name' => 'Laois'],
                ['code' => 'KK', 'name' => 'Kilkenny'],
                ['code' => 'WD', 'name' => 'Waterford'],
                ['code' => 'C', 'name' => 'Cork'],
                ['code' => 'KY', 'name' => 'Kerry'],
                ['code' => 'LK', 'name' => 'Limerick'],
                ['code' => 'TN', 'name' => 'North Tipperary'],
                ['code' => 'TS', 'name' => 'South Tipperary'],
                ['code' => 'CE', 'name' => 'Clare'],
                ['code' => 'G', 'name' => 'Galway'],
                ['code' => 'MO', 'name' => 'Mayo'],
                ['code' => 'RN', 'name' => 'Roscommon'],
                ['code' => 'SO', 'name' => 'Sligo'],
                ['code' => 'LM', 'name' => 'Leitrim'],
                ['code' => 'DL', 'name' => 'Donegal'],
            ]
        );

        $nl = Country::whereCode('NL')->first();
        $nl->states()->createMany(
            [
                ['code' => 'DR', 'name' => 'Drenthe'],
                ['code' => 'FL', 'name' => 'Flevoland'],
                ['code' => 'FR', 'name' => 'Friesland'],
                ['code' => 'GE', 'name' => 'Gelderland'],
                ['code' => 'GR', 'name' => 'Groningen'],
                ['code' => 'LI', 'name' => 'Limburg'],
                ['code' => 'NB', 'name' => 'Noord-Brabant'],
                ['code' => 'NH', 'name' => 'Noord-Holland'],
                ['code' => 'OV', 'name' => 'Overijssel'],
                ['code' => 'UT', 'name' => 'Utrecht'],
                ['code' => 'ZE', 'name' => 'Zeeland'],
                ['code' => 'ZH', 'name' => 'Zuid-Holland'],
            ]
        );

        $gb = Country::whereCode('GB')->first();
        $gb->states()->createMany(
            [
                ["name" => "Aberdeenshire", "code" => "ABE"],
                ["name" => "Anglesey", "code" => "ALY"],
                ["name" => "Angus", "code" => "ANG"],
                ["name" => "Argyll", "code" => "ARG"],
                ["name" => "Ayrshire", "code" => "AYR"],
                ["name" => "Banffshire", "code" => "BAN"],
                ["name" => "Bedfordshire", "code" => "BED"],
                ["name" => "Berkshire", "code" => "BER"],
                ["name" => "Berwickshire", "code" => "BWS"],
                ["name" => "Brecknockshire", "code" => "BRE"],
                ["name" => "Buckinghamshire", "code" => "BUC"],
                ["name" => "Bute", "code" => "BUT"],
                ["name" => "Caernarfonshire", "code" => "CAE"],
                ["name" => "Caithness", "code" => "CAI"],
                ["name" => "Cambridgeshire", "code" => "CAM"],
                ["name" => "Cardiganshire", "code" => "CAR"],
                ["name" => "Carmarthenshire", "code" => "CMS"],
                ["name" => "Cheshire", "code" => "CHE"],
                ["name" => "Clackmannanshire", "code" => "CLA"],
                ["name" => "Cleveland", "code" => "CLE"],
                ["name" => "Cornwall", "code" => "COR"],
                ["name" => "Cromartyshire", "code" => "CRO"],
                ["name" => "Cumberland", "code" => "CBR"],
                ["name" => "Cumbria", "code" => "CUM"],
                ["name" => "Denbighshire", "code" => "DEN"],
                ["name" => "Derbyshire", "code" => "DER"],
                ["name" => "Devon", "code" => "DEV"],
                ["name" => "Dorset", "code" => "DOR"],
                ["name" => "Dumbartonshire", "code" => "DBS"],
                ["name" => "Dumfriesshire", "code" => "DUM"],
                ["name" => "Durham", "code" => "DUR"],
                ["name" => "East Lothian", "code" => "ELO"],
                ["name" => "Essex", "code" => "ESS"],
                ["name" => "Flintshire", "code" => "FLI"],
                ["name" => "Fife", "code" => "FIF"],
                ["name" => "Glamorgan", "code" => "GLA"],
                ["name" => "Gloucestershire", "code" => "GLO"],
                ["name" => "Hampshire", "code" => "HAM"],
                ["name" => "Herefordshire", "code" => "HER"],
                ["name" => "Hertfordshire", "code" => "HTF"],
                ["name" => "Huntingdonshire", "code" => "HUN"],
                ["name" => "Inverness", "code" => "INV"],
                ["name" => "Kent", "code" => "KEN"],
                ["name" => "Kincardineshire", "code" => "KCD"],
                ["name" => "Kinross-shire", "code" => "KIN"],
                ["name" => "Kirkcudbrightshire", "code" => "KIR"],
                ["name" => "Lanarkshire", "code" => "LKS"],
                ["name" => "Lancashire", "code" => "LAN"],
                ["name" => "Leicestershire", "code" => "LEI"],
                ["name" => "Lincolnshire", "code" => "LIN"],
                ["name" => "London", "code" => "LON"],
                ["name" => "Manchester", "code" => "MAN"],
                ["name" => "Merionethshire", "code" => "MER"],
                ["name" => "Merseyside", "code" => "MER"],
                ["name" => "Middlesex", "code" => "MDX"],
                ["name" => "Midlands", "code" => "MID"],
                ["name" => "Midlothian", "code" => "MLT"],
                ["name" => "Monmouthshire", "code" => "MON"],
                ["name" => "Montgomeryshire", "code" => "MGY"],
                ["name" => "Moray", "code" => "MOR"],
                ["name" => "Nairnshire", "code" => "NAI"],
                ["name" => "Norfolk", "code" => "NOR"],
                ["name" => "Northamptonshire", "code" => "NMP"],
                ["name" => "Northumberland", "code" => "NUM"],
                ["name" => "Nottinghamshire", "code" => "NOT"],
                ["name" => "Orkney", "code" => "ORK"],
                ["name" => "Oxfordshire", "code" => "OXF"],
                ["name" => "Peebleshire", "code" => "PEE"],
                ["name" => "Pembrokeshire", "code" => "PEM"],
                ["name" => "Perthshire", "code" => "PER"],
                ["name" => "Radnorshire", "code" => "RAD"],
                ["name" => "Renfrewshire", "code" => "REN"],
                ["name" => "Ross & Cromarty", "code" => "ROS"],
                ["name" => "Roxburghshire", "code" => "ROX"],
                ["name" => "Rutland", "code" => "RUT"],
                ["name" => "Selkirkshire", "code" => "SEL"],
                ["name" => "Shetland", "code" => "SHE"],
                ["name" => "Shropshire", "code" => "SHR"],
                ["name" => "Somerset", "code" => "SOM"],
                ["name" => "Staffordshire", "code" => "STA"],
                ["name" => "Stirlingshire", "code" => "STI"],
                ["name" => "Suffolk", "code" => "SUF"],
                ["name" => "Surrey", "code" => "SUR"],
                ["name" => "Sussex", "code" => "SUS"],
                ["name" => "Sutherland", "code" => "SUT"],
                ["name" => "Tyne & Wear", "code" => "TYN"],
                ["name" => "Warwickshire", "code" => "WAR"],
                ["name" => "West Lothian", "code" => "WLO"],
                ["name" => "Westmorland", "code" => "WES"],
                ["name" => "Wigtownshire", "code" => "WIG"],
                ["name" => "Wiltshire", "code" => "WIL"],
                ["name" => "Worcestershire", "code" => "WOR"],
                ["name" => "Yorkshire", "code" => "YOR"],
            ]
        );
        $pl = Country::whereCode('PL')->first();
        $pl->states()->createMany(
            [
                ["name" => "Dolnośląskie", "code" => "DS"],
                ["name" => "Kujawsko-Pomorskie", "code" => "KP"],
                ["name" => "Lubelskie", "code" => "LU"],
                ["name" => "Lubuskie", "code" => "LB"],
                ["name" => "Łódzkie", "code" => "LD"],
                ["name" => "Malopolskie", "code" => "MA"],
                ["name" => "Mazowieckie", "code" => "MZ"],
                ["name" => "Opolskie", "code" => "OP"],
                ["name" => "Podkarpackie", "code" => "PK"],
                ["name" => "Podlaskie", "code" => "PD"],
                ["name" => "Pomorskie", "code" => "PM"],
                ["name" => "Śląskie", "code" => "SL"],
                ["name" => "Świętokrzyskie", "code" => "SK"],
                ["name" => "Warmińsko-Mazurskie", "code" => "WN"],
                ["name" => "Wielkopolskie", "code" => "WP"],
                ["name" => "Zachodniopomorskie", "code" => "ZP"],

            ]
        );
    }

}
